### ISSUE TITLE
ANTIGONE parameter file 

### ISSUE THREAD

**Issue by schlanghorvetz** [GAMS-dev/gams.jl#15]
When I specify a parameter for ANTIGONE (e.g. set_optimizer_attribute(model,"feas_tolerance", 1e-14)), I get the following error
*** Error Cannot open parameter file "/tmp/gams_jl_lOie8z/antigone.opt"
*** Error Error code = 2; No such file or directory
Is this error coming from my settings or the package.

Thanks!

**Comment by renkekuhlmann** [comment]
Thanks for reporting. I assume this is the same bug as described [here](https://discourse.julialang.org/t/unable-to-set-parameter-for-gams-package/82780/4) meaning that when you use lowercase everything is fine?

**Comment by renkekuhlmann** [comment]
Fixed with c2ce6102dcb0664f37e48fefde28c620165fb22f and released with version 0.3.4. Thanks again for reporting!
