### ISSUE TITLE
ANTIGONE parameter file

### ISSUE THREAD

**Issue by schlanghorvetz** [GAMS-dev/gams.jl#16]
When I specify a parameter for ANTIGONE (e.g. set_optimizer_attribute(model,"feas_tolerance", 1e-14)), I get the following error
*** Error Cannot open parameter file "/tmp/gams_jl_lOie8z/antigone.opt"
*** Error Error code = 2; No such file or directory
Is this error coming from my settings or the package.

Thanks!

**Comment by renkekuhlmann** [comment]
This seems to be a duplicate of #15.
