### ISSUE TITLE
MathOptInterface deprecated with some newer Julia packages

### ISSUE THREAD

**Issue by jcsyme** [GAMS-dev/gams.jl#17]
Hi, I'm trying to install GAMS.jl to access some solvers to use in JuMP along with NemoMod, which requires MathOptInterface 1.2+ (currently have 1.8.2, the latest, installed). 

However, it appears as though GAMS.jl is restricted to using these versions: [0.9.13-0.9.22, 0.10.7-0.10.9].

Are there any plans to update the MathOptInterface requirements for GAMS? Is this possible to do?

Here's the error in Pkg.add("GAMS"):

```
Unsatisfiable requirements detected for package MathOptInterface [b8f27783]:
 MathOptInterface [b8f27783] log:
 ├─possible versions are: 0.5.0-1.8.2 or uninstalled
 ├─restricted to versions 1.2.0-1 by NemoMod [a3c327a0], leaving only versions 1.2.0-1.8.2
 │ └─NemoMod [a3c327a0] log:
 │   ├─possible versions are: 1.8.0 or uninstalled
 │   └─NemoMod [a3c327a0] is fixed to version 1.8.0
 └─restricted by compatibility requirements with GAMS [1ca51c6a] to versions: [0.9.13-0.9.22, 0.10.7-0.10.9] — no versions left
   └─GAMS [1ca51c6a] log:
     ├─possible versions are: 0.1.0-0.3.4 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.3.4
```

**Comment by renkekuhlmann** [comment]
Upgrading to MathOptInterface 1.x has been on my list for quite a while now. Thanks for remembering me 👍 I'll look into it!

**Comment by jcsyme** [comment]
Awesome! Looking forward to testing it out.
