### ISSUE TITLE
Question: using PATH through GAMS

### ISSUE THREAD

**Issue by Jovansam** [GAMS-dev/gams.jl#2]
I have been hoping that something like this is developed. Great work!

But how does one use the PATH solver here. For example to solve the following simple problem:

```
x >=    0
2x - 1 ⟂ x
```

**Comment by odow** [comment]
GAMS.jl doesn't support complementarity constraints yet. You will have to use `PATH.jl` directly.

**Comment by renkekuhlmann** [comment]
Thanks for the feature request. I haven't addressed complementarity constraints yet, because I haven't seen them in the list of [supported MathOptInterface constraints](https://jump.dev/MathOptInterface.jl/v0.1.0/apimanual.html#Sets-1). I was not aware of [MathOptInterface.Complements](https://jump.dev/MathOptInterface.jl/v0.9.14/apireference/index.html#MathOptInterface.Complements). I will look into this.

**Comment by Jovansam** [comment]
@odow. PATH.jl is great. Tried out some test problems. Quite pleased.

@renkekuhlmann. Nice that I for one can make use of the GAMS solvers I have access to. PATH would be great additional to have eventually.

**Comment by sarkispa** [comment]
@Jovansam There is a [Complementarity.jl](https://github.com/chkwon/Complementarity.jl) package as well which I've used to do the same job as I once did in GAMS (solving large Nash-Cournot models).

**Comment by Jovansam** [comment]
@sarkispa thanks very much for the heads up. I tested my model out and it [works](https://discourse.julialang.org/t/julia-jump-optimization-help/43259).

**Comment by renkekuhlmann** [comment]
Support of complementarity constraints has been added to GAMS.jl (v0.2.0). If complementarity constraints are detected in the model, GAMS.jl will set the model type to MPEC. If you want to use the GAMS type MCP instead (having no objective function), please call:
```
set_optimizer_attribute(model, GAMS.ModelType(), "MCP")
```

Sorry, for the very long delay to support this feature. This was a very good training task for a new student, so this required some extra learning time. Please let us know, if you think there is something that can be improved for this feature. Thanks again very much for posting the feature request!
