### ISSUE TITLE
GeneratedConstraintName() for Non linear constraints

### ISSUE THREAD

**Issue by jagomezm4** [GAMS-dev/gams.jl#23]
I need to find the name with which a Julia equation is set in GAMS on an NLP formulation. However, the  GeneratedConstraintName() function does not work with the @NLconstraint object. Is there any other way to see how equations are named in GAMS?

**Comment by renkekuhlmann** [comment]
Sorry for not replying for so long. I was on parental leave for some time and just started working again. I was not aware of this issue with nonlinear constraints and will look into it. Thanks for reporting!

**Comment by odow** [comment]
JuMP's `@NL` nonlinear constraints do not really support names.

This limitation is fixed in the upcoming nonlinear rewrite: https://github.com/jump-dev/JuMP.jl/pull/3106

**Comment by renkekuhlmann** [comment]
Thanks @odow for pointing this out!

**Comment by renkekuhlmann** [comment]
With v0.5.0 GAMS.jl supports `MOI.ScalarNonlinearFunction` which in turn supports names. For those nonlinear constraints `GeneratedConstraintName` will work. Thanks for your patience!
