### ISSUE TITLE
Support MOI.ScalarNonlinearFunction

### ISSUE THREAD

**Issue by Downsite** [GAMS-dev/gams.jl#25]
Within https://github.com/jump-dev/JuMP.jl/pull/3106, MathOptInteface has upgraded its support for nonlinear modeling.
A very nice feature is better support of "function  tracing", which better supports building models programmatically.

I would be exited to use this feature with GAMS in Julia.

Perhaps you could take a look at the changes done to Baron.jl and see if it is easy to adapt this wrapper.

**Comment by renkekuhlmann** [comment]
Thanks for this suggestion. I'll have a look.

**Comment by Downsite** [comment]
Meanwhile, a workaround is saving the constructed model to file and reading it with  `use_nlp_block = true`
```
    readprob = MOI.FileFormats.Model(format =  MOI.FileFormats.FORMAT_MOF,use_nlp_block = true)
    MOI.read_from_file(readprob, "temp_model.mof.json")
    model = Model(GAMS.Optimizer)
    MOI.copy_to(model,readprob)
```

maybe there is a more elegant way, but this works.

**Comment by renkekuhlmann** [comment]
`MOI.ScalarNonlinearFunction` will be supported with v0.5.0 (should be available for update very soon). Thanks again for making me aware of this! If you experience any issues, don't hesitate to create a new issue.
