### ISSUE TITLE
User Model Type not used 

### ISSUE THREAD

**Issue by Downsite** [GAMS-dev/gams.jl#27]
Some of my models might contain the "abs" function.
Before, GAMS would complain that I did not specify "DNLP", so I would just set the model type to "MINLP" (since I want to solve with Baron anyways).

`set_optimizer_attribute(model, GAMS.ModelType(), "MINLP")`

In the latest 0.4.3 version, this still worked, but it seems to be ignored in the 0.5 versions.
Thus, even after setting the problem type as shown above, "NLP" is written to the .gms file.

**Comment by renkekuhlmann** [comment]
Sorry for this. I can reproduce the issue and will fix it very soon.

**Comment by renkekuhlmann** [comment]
Fixed with v0.5.2. Hope that all the bugs from the refactor for the ScalarNonlinearFunctions are resolved and your code is running again! :-)
