### ISSUE TITLE
is it possible to access dual/marginal variables

### ISSUE THREAD

**Issue by Jovansam** [GAMS-dev/gams.jl#3]
I was trying to access a dual variable by way of JuMP.dual(x). I could not and got the following.

>ModelLike of type GAMS.Optimizer does not support accessing the attribute MathOptInterface.NLPBlockDual(1)

**Comment by renkekuhlmann** [comment]
I can confirm the bug. I'll will work on a fix.

**Comment by renkekuhlmann** [comment]
I added support for MOI.NLPBlockDual on the master branch. I'll release a fixed version later. In the meantime, you may want to test with the master branch. Thanks for submitting the issue!
