### ISSUE TITLE
GAMS doesn't recognize "acos"

### ISSUE THREAD

**Issue by Jovansam** [GAMS-dev/gams.jl#8]
Hi,
GAMS.jl has a problem with 'acos'. In GAMS (as opposed to Julia-JuMP) it is called arccos. Might there be a translation problem?
See problem line:
```
    @NLexpression(DPVI, V̂[i=SN, j=Sdeg], coefs[j] * cos((j - 1) * acos(dz * (kPlus[i] - extkmin) - 1)) )
```

**Comment by renkekuhlmann** [comment]
Absolutely! Thanks for reporting this issue. Will be fixed shortly.

**Comment by renkekuhlmann** [comment]
Has been fixed with GAMS.jl version 0.2.2 (available in package manager very soon). Also added support of `asin`, `atan`, `mod` and `sign`. Thanks again for pointing out this issue!
